DROP TABLE ADVERTISEMENTSTATS IF EXISTS;

CREATE TABLE ADVERTISEMENTSTATS  (
    id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    datasource VARCHAR(60),
    campaign VARCHAR(60),
    daily DATE,
    clicks DECIMAL(100, 4),
    impressions DECIMAL(100, 4)
);